// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ssqpyvfrcfmnvrdmouty.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzcXB5dmZyY2ZtbnZyZG1vdXR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NTgxMjAsImV4cCI6MjA1ODEzNDEyMH0.y-cz1p3OlCNx2eGQQ66O_HKqoA5PWZvGnP_k0c9aPSQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);